# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZU8F-Lp97cIhHwsz36ilERTJCxJ58iy
"""

# Importando bibliotecas necessárias
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings("ignore", message="X does not have valid feature names") # Gambiarra LOL ;p

# Carregando o dataset com os dados históricos de empréstimos
dataset = pd.read_csv('/content/dados_emprestimo.csv')

### Pré-processamento dos dados ###

# Separando os dados em atributos (X) e rótulos (y)
X = dataset.drop('Risco', axis=1)  # Atributos
y = dataset['Risco']  # Rótulos

# Dividindo o conjunto de dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criando o modelo de classificação
modelo = DecisionTreeClassifier()

# Treinando o modelo
modelo.fit(X_train, y_train)

# Realizando previsões no conjunto de teste
y_pred = modelo.predict(X_test)

# Avaliando a acurácia do modelo
acuracia = accuracy_score(y_test, y_pred)
print(f'Acurácia do modelo: {acuracia}')

# Realizando a previsão para um novo exemplo
novo_exemplo = [[37,4,74245,4500]] # Risco Alto
novo_exemplo = [[47,1,58381,516]] # Risco Baixo
risco = modelo.predict(novo_exemplo)
print(f'Risco de empréstimo para o novo exemplo: {risco}')